### ISSUE TITLE
How to publish the "Accompanying Guideline"?

### ISSUE THREAD

**Issue by peterlubrich** [mobilityDCAT-AP/mobilityDCAT-AP#11]
As announced, we are planning an additional document to mobilityDCAT-AP:
the "Accompanying Guideline"!

-> It should be an extra document outside our ReSpec, to be published later this year.

So far, we are collecting inputs and contents on [Sharepoint](https://rupprechtconsultde.sharepoint.com/:f:/r/sites/NAPCOREallpartners/Shared%20Documents/SubWG4.4/Work%20Items/Work%20Item%204.4.3.3%20Support%20%26%20dissemination%20to%20NAP%20operators/Accompanying%20Guideline?csf=1&web=1&e=tmcOhk):

I think it's better to make an online version of this, rather than an "oldschool" NAPCORE pdf.
This way, we can update it regularly, publish it at a prominent place, and insert links to external resources (e.g.,  directing to elements of mobilityDCAT-AP which are explained in the Guideline.)

-> In the end, it will be a mix of text (with (sub-) chapters), FAQs, some figures and references (hyperlinks).
-> Does anyone have an idea how to publish such online version ?
-> I think another ReSpec page is too much!
-> But maybe as a GitHub Pages-Website, which we can host on our regular repository?

Thanks!

**Comment by lcomet** [comment]
@peterlubrich I agree with your suggestion of having a GitHub Page in which we present the documentation in a simple and structured way. In my opinion, there is no need to create a ReSpec or any other technical-like documentation with additional tools.

**Comment by marioscrock** [comment]
@peterlubrich @lcomet I agree too. We can define a Markdown file and host it through Github Pages (same visualisation as for the README at https://mobilitydcat-ap.github.io/mobilityDCAT-AP/) or we can use the Wiki functionality (check for example this page https://github.com/SEMICeu/DCAT-AP/wiki/Submission-guidelines). In both cases when finalised we can also define a redirection rule from a URL like w3id.org/mobilitydcat-ap/guidelines.

**Comment by lcomet** [comment]
Indeed, I just created a Wiki initial page in our repository https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/wiki
We can document the accompanying guidelines there.

**Comment by burespe1** [comment]
Agree, as an example there is nice ISO page with terminology, that has both
wiki and website hosted on the ghpages.
GitHub - ISO-TC204/iso14812: Intelligent transport systems - Vocabulary
<https://github.com/ISO-TC204/iso14812>
<https://github.com/ISO-TC204/iso14812>
Petr Bureš
email: ***@***.***
mob.: (+420) 777 131 603


st 23. 8. 2023 v 12:28 odesílatel Lina Molinas Comet <
***@***.***> napsal:

**Comment by BWitsch** [comment]
I would also pefere a simple Github page for showing Specifications, documents and additional informations.

**Comment by evathelisson** [comment]
I just created a GitHub account. I am in favor of a simple Github page as well. It should be easy to edit. Thanks.
