### ISSUE TITLE
Distribution: schema download link and corresponding documentation

### ISSUE THREAD

**Issue by keesnieuwstad** [mobilityDCAT-AP/mobilityDCAT-AP#13]
For a Distribution, I see the property mobilitydcatap:dataModelSchema. Its description is: “This property describes the schema of the delivered content, as applied for the data model, see property mobilitydcatap:dataModel). The schema can be individually determined by the data provider (e.g., a stakeholder-based DATEX II profile) or a prescribed by other institutions (e.g., a DATEX II recommended reference profile). […]”

I do not quite understand how I have to read this; it reads like “a description of the schema/XSD has to be given in this property”. But XSD in itself is a description.

1. If we take DATEX II as an example, would it not be more, or also, suitable to provide the option to add to a distribution a download link to the schema (XSD)? (Say, maybe dataModelSchemaDownloadURL?)

2. Lots of elaborate documentation about DATEX II profiles (schemas) is given, for example on websites (datex2.eu). If mobilityDCAT-AP would allow to give a link to a schema for download, a property (say, maybe DataModelDocumentationURL) to point to the corresponding documentation for this schema would, in my opinion, be very good to have.

**Comment by peterlubrich** [comment]
Regarding "I do no understand...":
We will refine the usage note as follows:
"This property refers to a data schema associated with the applied data model, see property mobilitydcatap:dataModel."

Regarding 1:
You propose to change the range of this property from "rdfs:Resource" to "dcat:Distribution". 
If we do so, the schema information would need to include any mandatory properties from the class "dcat:Distribution", see:
https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#properties-for-distribution

This would unnecessarily explode the payload: For example, the property "mobilitydcatap:dataModel" would need to be noted again, which is equal to "mobilitydcatap:dataModel" of the original distribution.
I propose to keep the generic range "rdfs:Resource".

Regarding 2:
If we keep the range "rdfs:Resource" (see above), the NAP system can decide how to reference the schema. It might be a URL to a NAP-internal catalogue of schemas, a URL to an individual schema (that is provided by the metadata publisher), or a URL to an external catalogue of schemas (like on the datex2.eu page). I will add this as a usage note.

I propose NOT to not include any additional properties for mobilityDCAT-AP1.0. We have only a few days until the publication, and property additions would involve another review round. However, let's think about refinements of our format-related properties (which may be expressed as formal sub-properties) for mobilityDCAT-AP2.0.

**Comment by keesnieuwstad** [comment]
Thanks for the proposals.

I was not aware that there are (only) a few days left until the release of version 1.0. So, it's nice that the usage note of 1 and 2 can still be adjusted.

To see later whether it is desirable to further develop format-related properties, looks like a sensible route to me.

**Comment by peterlubrich** [comment]
I resolved this while resolving this issue:
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/12
See point 2.
-> There is a dedicated new class "Mobility Data Standard", with a property "Schema".
-> The range of "Schema" is kept with "rdfs:Resource", for the reasons above.
-> The usage of "Schema" has been concretised, with the options how to describe a schema described above.
