### ISSUE TITLE
Dataset property dct:language is mandatory, does not explain what to do if a dataset has no language

### ISSUE THREAD

**Issue by hildea** [mobilityDCAT-AP/mobilityDCAT-AP#15]
The comment for this property says _"This property refers to a language of content data, **if** this data has a natural language embedded."_
If we are going to keep this property as mandatory, there must be some guidance for how to fill it in for data that do **not** have a natural language embedded.

> language | dct:language | dct:LinguisticSystem | This property refers to a language of content data, if this data has a natural language embedded. Such data contents include text fields, addresses etc. This property can be repeated if there are multiple languages in the Dataset - see § 8. Accessibility and Multilingual Aspects. A controlled vocabulary § 5.2 Controlled vocabularies to be used is provided.The obligation of this property is raised to “mandatory”, compared to [DCAT-AP-v2.0.1].
> 
> The obligation of this property is raised to “mandatory”, compared to [[DCAT-AP-v2.0.1](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#bib-dcat-ap-v2.0.1)].

**Comment by peterlubrich** [comment]
Resolution:  change property from "mandatory" to "recommended"?

**Comment by peterlubrich** [comment]
I changed this property to "optional", as in original DCAT-AP v2.
