### ISSUE TITLE
"rights holder" comment says this is contact point for questions about the data set, not correct in all cases

### ISSUE THREAD

**Issue by hildea** [mobilityDCAT-AP/mobilityDCAT-AP#16]
In the comments about rights holder, the sentence _"This entity is the direct contact for the platform operator or data consumers, who have questions or issues about the contents of a dataset."_ does not fit the reality for many datasets. For instance a dataset of all public transport timetables in a country, where each transport operator will be listed as a rights holder, but the dataset is maintained by a national entity who will be the preferred contact point for questions about the dataset.

> +rights holder
> dct:rightsHolder
> foaf:Agent
> This property refers to an entity that legally owns or holds the rights of the data provided in a dataset. This entity is legally responsible for the content of the data. It is also responsible for any statements about the data quality (if applicable, see property [dqv:hasQualityAnnotation](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#dataset-quality-description)) and/or the relevance to legal frameworks (if applicable, see property [dcatap:applicableLegislation](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#dataset-applicable-legislation)).
> 
> **This entity is the direct contact for the platform operator or data consumers, who have questions or issues about the contents of a dataset.**

**Comment by peterlubrich** [comment]
This is overlapping with another comment from SEMIC.
See:
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/14
...point 1.

-> I need to re-introduce the "contact point" property, which will be the only interaction point between data providers and data users. In contrast, "publisher" and "rights holder" will be organisations that (technically/legally) represent the data set.
-> This change should resolve your issue.

The conflict between "contact point" vs. "organisation" was already discussed before us ;-)
https://joinup.ec.europa.eu/release/how-are-publisher-and-contact-point-modelled

**Comment by peterlubrich** [comment]
See the resolved issue:
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/14
...point 1.
->Agent information and contact point information is now separated.
->"rights holder" is not anymore used to establish a contact with data users.
