### ISSUE TITLE
Download of SHACL (Turtle) file fails

### ISSUE THREAD

**Issue by keesnieuwstad** [mobilityDCAT-AP/mobilityDCAT-AP#2]
On [this](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/) page I can click on a download link for a SHACL (Turtle) file. However, clicking the link results a 404 Page not found. Can this be fixed?

**Comment by lcomet** [comment]
Thank you for reporting this issue. As currently we do not have a SHACL file, I removed the link to download such a file. In the future, we will include this option.
