### ISSUE TITLE
Typos to be fixed

### ISSUE THREAD

**Issue by marioscrock** [mobilityDCAT-AP/mobilityDCAT-AP#20]
List here typos to be fixed for the next release

**Comment by marioscrock** [comment]
"This is a sub-property of dct:conformsTodct:conformsTo." in Section 4.11.3 2nd row of the table

**Comment by marioscrock** [comment]
Last line in the Table in Section 5.2, should it be dct:rights instead of dct:type?

**Comment by marioscrock** [comment]
In the specification, in some cases, the wrong URI is used for the class mobilitydcatap:MobilityDataStandard, e.g., in https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#properties-for-mobility-data-standard. The URI with the uppercase "M" should be used for the class and the one with the lowercase "m" for the property.

Ref to issue #19

**Comment by peterlubrich** [comment]
> Last line in the Table in Section 5.2, should it be dct:rights instead of dct:type?

Well, have a look:
"type" is a property of class "Rights Statement". Class "Rights Statement" is the range of property "rights". And "rights" is a property of class "Distribution".
The Controlled Vocabulary is indeed introduced for "type", denoting a predefined option for this property. So, everything is correct here!

**Comment by peterlubrich** [comment]
Typos corrected in v1.0.1:
"This is a sub-property of dct:conformsTo." 
mobilitydcatap:MobilityDataStandard vs. mobilitydcatap:MobilityDataStandard 

Regarding "dct:rights instead of dct:type":
Ongoing discussion between Peter and Mario. Option: property change as part of a future major revision.

**Comment by marioscrock** [comment]
> Regarding "dct:rights instead of dct:type": Ongoing discussion between Peter and Mario. Option: property change as part of a future major revision.

Thank you @peterlubrich for clarifying that this is not a typo. The `dct:type` property is recommended to connect an individual of class `dct:RightsStatements` to a value in the controlled vocabulary (and **not** to connect a `dcat:Distribution` to the associated `dct:RightsStatements`). I got confused because, in the other tables, we have the column `Property` and then the column `Range`, while in Section 5.2 the second column is `Used for Class`.
