### ISSUE TITLE
Catalog class: no service proprerty

### ISSUE THREAD

**Issue by Bfrichet2** [mobilityDCAT-AP/mobilityDCAT-AP#21]
Dear

I noticed in your mobilityDCAT-AP profile there are no [service proprety](https://www.w3.org/ns/dcat#service) in the [Catalog ](http://www.w3.org/ns/dcat#Catalog)object type. This property is to be used in order to specify or to document any Data Service in the considered Catalog.

I think this is a very surprising position as that property is "Recommended" in the current version of DCAT AP 3 (https://semiceu.github.io/DCAT-AP/releases/3.0.0/#quick-reference) and Service object type is explicitly specified in mobilityDCAT AP.

Therefore I strongly recommend to define the [service proprety](https://www.w3.org/ns/dcat#service) in this profile in order to reference any Data Service in the meaning of DCAT standards.

Regards,

**Comment by peterlubrich** [comment]
Yes, this have been discussed many times!

For the initial release of mobilityDCAT-AP, it was decided to only support metadata in existing mobility data portals. After a deeper analysis, all existing portals (=catalogs) only list metadata about datasets, and NOT about data services  (e.g., APIs). In the future, we might re-introduce the service property under the Catalogue. For now, we want to keep mobilityDCAT-AP as compact, not using any properties without practical relevance for mobility portals.

See also the [usage notes under the Class "Data Service"](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#properties-for-data-service).

**Comment by marioscrock** [comment]
@Bfrichet2 thank you for your feedback on this topic! As commented by @peterlubrich and described in the specification we decided not to introduce the Data Service class in this release of mobilityDCAT-AP. I will close this issue but add a reference to the one related to the alignment with DCAT-AP v3 since we may want to discuss this further when planning the next major release.
