### ISSUE TITLE
Dataset class: mandatory frequency proprety

### ISSUE THREAD

**Issue by Bfrichet2** [mobilityDCAT-AP/mobilityDCAT-AP#22]
Dear

I noticed in your mobilityDCAT-AP profile [frequency property](http://purl.org/dc/terms/accrualPeriodicity) is a [MUST ](https://datatracker.ietf.org/doc/html/rfc2119#section-1)in the meaning of 1st section of RFC 2119 in the definition of the [Dataset object type](http://www.w3.org/ns/dcat#Dataset). 

This is a clear restriction regarding to DCAT AP specifications as both [DCAT AP 2](https://joinup.ec.europa.eu/sites/default/files/distribution/access_url/2019-12/12f0dc1d-50b6-43e4-90c2-0afe213ac2be/DCAT_AP_2.0.0.pdf) and [3 ](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#quick-reference)set this property as [OPTIONNAL ](https://datatracker.ietf.org/doc/html/rfc2119#section-5)in the meaning of ther 5th section of RFC 2119.

Therefore I would align the requirement 

I think this is a very surprising position as that property is "Recommended" in the current version of DCAT AP 3 (https://semiceu.github.io/DCAT-AP/releases/3.0.0/#quick-reference). Many data provider in my country do not maintain such an information. Moreover this is not a metadata element that is required for [INSPIRE dataset](http://data.europa.eu/eli/reg/2008/1205/2008-12-24) which means INSPIRE datasets won't have such a property on the one hand or this will go against once only principle on the other hand.

Therefore I strongly recommend to specify this property as [OPTIONNAL ](https://datatracker.ietf.org/doc/html/rfc2119#section-5)or as [RECOMMANDED ](https://datatracker.ietf.org/doc/html/rfc2119#section-3)in the meaning of 5th and 3rd sections of RFC 2119.

Regards,

**Comment by peterlubrich** [comment]
mobilityDCAT-AP is an extension to DCAT-AP.
Following the [DCAT-AP extension guidelines](https://joinup.ec.europa.eu/release/dcat-ap-how-extend-dcat-ap), we are allowed to raise obligation levels of classes or properties. We are doing so in several cases, when we feel that certain metadata information is crucial for mobility data.
Mobility data may have update cycles between 1 year (maybe geodata) and 1 millisecond (Automated Driving) . Thus, mobility datasets should be distinguishable via this property, so it is mandatory.

**Comment by Bfrichet2** [comment]
@peterlubrich thank you for your answer. As some dcat:Dataset are created from the INSPIRE legal framework and as the INSPIRE metadata does not include anything concerning update frequency it is quite clear to me that this property won't be provided in that case (at least without revision of EC 1205/2008 Regulation). In that perspective I strongly recommend to specify as a SHOULD and not as MUST otherwise you already know that many dcat:Dataset aren't to be compliant with this non-legally binding profile.
