### ISSUE TITLE
Dataset class: mobility theme

### ISSUE THREAD

**Issue by Bfrichet2** [mobilityDCAT-AP/mobilityDCAT-AP#23]
Dear

I noticed in your mobilityDCAT-AP profile [moility themeproperty](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#dataset-mobility-theme) is a [MUST ](https://datatracker.ietf.org/doc/html/rfc2119#section-1)in the meaning of 1st section of RFC 2119 in the definition of the [Dataset object type](http://www.w3.org/ns/dcat#Dataset).

This is a from new property added by Mobility DCAT AP which becomes an extension of DCAT AP rather than an application profile or a specification. In my opinion this is not a good practice at all and this is to be avoided as that new attribute won't be understood or taken into account by most of its readers that don't expect such an attribute. 

Therefore I strongly recommend to stick to the [theme property ](https://www.w3.org/ns/dcat#theme) that had been designed for that purpose by both DCAT an DCAT AP custodians. If you want a specific vocab to be mentioned (i.e. [your own vocab](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#bib-euv-themes-transport)) you should require as a [MUST ](https://datatracker.ietf.org/doc/html/rfc2119#section-1) in the meaning of the 1st section of RFC 2119 the skos:inScheme property in the skos:Concept object type and you should ask for an unambiguous reference to that specific vocab in that property. This is much more interoperable and standard and once only friendly way of specifying a vocab.

Regards,

**Comment by peterlubrich** [comment]
Hello,
I don't really understand the advice. 

I was recommended by the SEMIC authors to link to an own, extension-specific Controlled Vocabulary for the "theme" via a new property,  This is what we did with the property [mobilitydcatap:mobilityTheme](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#dataset-mobility-theme). That approach was even referenced by the [ SEMIC style guide](https://joinup.ec.europa.eu/collection/semic-support-centre/application-profiles-what-are-they-and-how-model-and-reuse-them-properly-look-through-dcat-ap#:~:text=4.%20Incoherence%20between%20Application%20Profiles%20and%20Vocabularies) !
Citation:
"MobilityDCAT-AP avoided such inconsistency by adding a property mobilitydcatap:mobilityTheme, being a sub-property of dcat:theme. The new property links to a new controlled vocabulary, valid only for the mobility extension. In addition, the DCAT-AP property dcat:theme is still valid under the extension, and links to the controlled vocabulary prescribed by DCAT-AP. This way, both controlled vocabularies can be used without interference."

And, yes, this new property is mandatory, as we see a mobility-specific theme taxonomy as crucial for metadata in our domain! 
And if a "reader" cannot handle that new property, it can ignore this information!

**Comment by Bfrichet2** [comment]
There are many discussions concerning the opportunity of creating sub-propreties and we had a long discussion concerning that specific point during the last GeO DCAT AP 3 workshop. In my opinion one should not create a subproprety but should give clear instructions about the content of the property.

**Comment by peterlubrich** [comment]
Hello Benoît,
thank you for your clarification. I understand the direction of "using vs. not using sub-properties" is under discussion. We (as the editors of mobilityDCAT-AP) were also not sure about this. 
However, after talks with Makx and Bert from DCAT-AP, we made this design decision. Means: the property [mobilitydcatap:mobilityTheme](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#dataset-mobility-theme) remains an essential part of our community vocabulary. 
We might revisit this design decision at a future major update of mobilityDCAT-AP. Then, we will consider your comments for sure. For now, I'd like to close this issue, if you dont mind.
Best,
Peter

**Comment by peterlubrich** [comment]
As discussed, might be a discussion item for a future major update of mobilityDCAT-AP.

**Comment by peterlubrich** [comment]
As discussed, might be a discussion item for a future major update of mobilityDCAT-AP.

**Comment by Bfrichet2** [comment]
@peterlubrich  you can close it for sure but that does not involve such dcat:Dataset objects will be broadcasted
