### ISSUE TITLE
1.0.0 repository: examples directory can be deleted?

### ISSUE THREAD

**Issue by peterlubrich** [mobilityDCAT-AP/mobilityDCAT-AP#24]
Seems there is a folder in the 1.0.0 directory that can be deleted:
see: "releases/1.0.0/examples"

Seems the files in this folder are still copies from the geoDCAT-AP repository (which we used as a baseline).
In 1.0.0, we didn't use any examples.
Suggestion: delete the entire example folder.

In 1.0.1., we will publish some example files, which will be saved in this future folder: "releases/1.0.1/examples

**Comment by marioscrock** [comment]
Related to #29

**Comment by lcomet** [comment]
I opted for deleting the example folders for the release and the draft versions. Consequently, I also deleted the related text in index.html referring to those examples.
As proposed by Peter we can add examples for the new draft/release, then we will include again similar text and files.

**Comment by marioscrock** [comment]
@lcomet the examples in the drafts/latest folder were correct and we added a proper text within the Appendix D with links. Only the examples referenced in Section 4 and the related text should be removed.

**Comment by lcomet** [comment]
@marioscrock thank you for the clarification. I assumed the examples were still the old ones and did not check them in detail. I reverted the deletion of the examples folder and text for the latest draft version.
