### ISSUE TITLE
Change description of the mobilityDCAT-AP repository and organisation 

### ISSUE THREAD

**Issue by marioscrock** [mobilityDCAT-AP/mobilityDCAT-AP#25]
To be changed:
- Add README to the organisation with link to the specification and relevant documents
- Specify it is not only for NAPs
- Change the link in the repo now pointing to NAPCORE news?

**Comment by peterlubrich** [comment]
Are your proposals related to the GitHub repository, or to the ReSpec page? Please specify which sections need an update.

**Comment by marioscrock** [comment]
The issue is related to the GitHub organisation and repository. I'm referring to the metadata in the repository:

![image](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/assets/5709852/f54c8d00-639f-40a6-b1c7-9bb66e109b07)

And the homepage of the organisation that can be also further customised with a README.

https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#organization-profile-readmes

![image](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/assets/5709852/cf8ce59a-96a8-4cef-83e1-03f7de257fe0)

**Comment by marioscrock** [comment]
Done
