### ISSUE TITLE
Future usage of property "conditions for access and usage" 

### ISSUE THREAD

**Issue by peterlubrich** [mobilityDCAT-AP/mobilityDCAT-AP#27]
For Distributions, we have the mandatory property "dct:rights" with cardinality 1..1. 
This leads to class "Rights Statement", which has a mandatory property "conditions for access and usage".
For this property, we are using the following Controlled Vocabulary:
https://mobilitydcat-ap.github.io/controlled-vocabularies/conditions-for-access-and-usage/latest/index.html#/

This Vocabulary is denoting pre-defined categories of "conditions for access and usage". The origin of this property and its Vocabulary is the Coordinated Metadata Catalogue. We took this over via the Conceptual Model, but made the value list a little more generic.

Old value list (CMC):
- No licence – No contract 
- Licence and Free of charge 
- Licence and Fee 
- Contract and Free of charge 
- Contract and Fee 
- Not relevant 

Current value list (our Controlled Vocabulary):
- Licence provided
- Contractual arrangement
- Free of charge
- Fee required
- Royalty-free
- Other

 However, there are some observations:
- The above value list is rarely used as metadata fields in existing NAPs.
- For new NAPs (e.g., in DK), it seems that concrete licenses are preferred (via another property "dct:license").
- Our value list seems a little naive (it has never been discussed with license experts). For example, there might be a combination of the values "Licence provided" and "Free of charge", which is not allowed with cardinality 1..1. 

Options:
- Check and verify the current value list 
- Change cardinality to 1..n.
- Make property recommended (instead mandatory) with cardinality 0..n.

**Comment by EdNDW** [comment]
Another option is to combine several possible options in the same way was done in the CMC. For example: 

- Licence provided and Free of charge
- Licence provided and Fee required
- Etc.

**Comment by burespe1** [comment]
We shall reuse as much as DCAT concepts as possible. 

Therefore I suggest we follow the reuse rule (pointed out above by @peterlubrich) and use property "dct:license" for informing about concrete licenses and keeping the original "conditions for access and usage" property for informing mainly about the paid or not payed (free of charge). later on we could remove the "conditions for access and usage" prooetry

This could be done by **wiki page** and published guideline there.

**Comment by CRVH** [comment]
Suggestion to  split the question/property in two: 
1. Recommend to have one field to ask: Is data for free or not? 
2. Ask the question (regardless the answer to the first) : "Is data shared under a licence? Either yes, no, or choose from a list of CC BY licence.  
I hope my suggestion is understandable.

**Comment by peterlubrich** [comment]
Meeting 24.06.24: complex story: licenses vs. access conditions - discuss again for major revision

**Comment by peterlubrich** [comment]
There seem to be an need to improve the license information, at least here for the NAP in Germany.
Comment from NAP operator:

> The field “Conditions for access and usage” (with the generic categories “Licence provided” etc.) is a relic from the old NAP days. The field “standard license”, on the other hand, comes from the open data scene and has also found its way into the NAP cosmos. Some prominent users of our NAP (e.g., Google Maps) are much more interested in the field “standard license”. We propose to  make the field “Conditions for access and usage” optional and make the field “standard license” mandatory instead. 

Proposal:
Take on as discussion item for future release of mobilityDCAT-AP
To be handled by new working group, see [issue 18](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/18)

**Comment by peterlubrich** [comment]
Proposal:

**Short-term action for mobilityDCAT-AP v1.1.0:**

- Change cardinality of current property ["conditions for access and usage"](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/index.html#rights-statement-conditions-for-access-and-usage) from 1..1 to 1..n
- This doesn't hurt and solves some of the current problems at,. e.g. , the German NAP


**Long-term action for mobilityDCAT-AP v3.0.0:**

- Discuss relations "conditions for access and usage" vs. "standard licenses" (see above)
- Decide about future use & definition of property "conditions for access and usage"

**Comment by burespe1** [comment]
How does changing the cardinality help the case? I would suggest to stick to the proposal https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/27#issuecomment-2068872147

**Comment by peterlubrich** [comment]
Okay, Petr.
Pleas help me understand your proposal [comment](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/27#issuecomment-2068872147):
_"keeping the original "conditions for access and usage" property for informing mainly about the paid or not payed (free of charge)"_
-> Do you want to change the [controlled vocab ](https://mobilitydcat-ap.github.io/controlled-vocabularies/conditions-for-access-and-usage/latest/index.html#/) behind "conditions for access and usage" ?
Meaning that only the values "Fee required" and "Free of charge" remain?

**Comment by peterlubrich** [comment]
I am also investigating current NAP implementations, to find out the best solutions for using "conditions for access and usage" in real NAPs.

1. Situation in DK NAP: They don't use this property at all. This means the cardinality would be changed from "1..1" to "0..1", if we follow the DK practice.
2. Situation in DE NAP: They want to use this property, however with multiple values. This means the cardinality would be changed from "1..1" to "1..n"

-> To address both NAP perspectives, the cardinality would be even more relaxed to "0..n" !!!
-> We need to consider, that any changes in our data model have to go along NAP practice. We are now behind the phase with "wishes" for elements of mobilityDCAT-AP (this was done in the Conceptual Model phase), now we are in the phase with clear practical expectations from real NAP operations. Everyone, please consider! 
-> Any suggestions?
-> @burespe1 : How is the expectation from the CZ NAP? Will they populate the "conditions for access and usage" with 1..1 values?

**Comment by peterlubrich** [comment]
I see there is no consensus between the two discussed options.
So, we will go for a formal vote in our meeting on Nov 4, 2024 with these options:

- OPTION 1:  Relax cardinality of property "conditions for access and usage" from 1..1 to 1..n. Reason: allow for combinations of values, such as "Licence provided" plus "Free of charge".
- OPTION 2:  Extend controlled vocabulary behind property "conditions for access and usage". Reason: allow for constellations such as "Licence provided, free of charge". 
- OPTION 3: do nothing

**Comment by burespe1** [comment]
Dear @peterlubrich, sorry for not responding earlier. We have two properties to express rights and licenses:

- Our property, "[**conditions for access and usage**](https://mobilitydcat-ap.github.io/controlled-vocabularies/conditions-for-access-and-usage/latest/index.html#/)" that defines whether there is a license and if there is a fee.
- The standard property used to inform about rights and licenses **dct:rights**. This property links to a rights statement that can include licensing information as well as other supplementary information, such as attribution.

Both properties are useful and complementary. I think we should use both: our property for recording general information about licenses and the standard property for linking specific licenses and accommodating "standard" queries.

My previous comment stemmed from the misunderstanding that we were ruling out the dct:rights property from the catalog structure. **This is not the case, and I apologize for the confusion.**

I have a slight preference for one of the options, but I will keep it for the vote. However, before the vote, we should discuss the pros and cons of both options

**Comment by kennethSorensenDK** [comment]
In DK we have the approach that the user always should choose a license, as we always require the user to choose which CC license they give to their dataset, therefor our users will always get the value "license provided". 
It is our recommendation that MobilityDCAT-AP aligns with existing standard licenses (Creative Commons). 
However, we have made it possible for our users to choose "other" if they have a special license. But the user will always have to make a reference of a licenses or upload a license.

**Comment by peterlubrich** [comment]
Meeting 05.12.2024:
Decision procedure for the proposed change:

_OPTION 1: Cardinality of property ["conditions for access and usage"](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#rights-statement-conditions-for-access-and-usage) changed from from 1..1 to 1..n. Reason: allow for combinations of values, such as "Licence provided" plus "Free of charge".  DECISION POINT: OPTION 1 / OPTION 2_


_OPTION 2: Extended [controlled vocabulary](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#vocab-conditionsforusage) behind property ["conditions for access and usage"](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#rights-statement-conditions-for-access-and-usage). Reason: allow for constellations such as "Licence provided, free of charge".  DECISION POINT: OPTION 1 / OPTION 2_

**Decision result: 
OPTION 1:  BE, NL, IT - 3 votes
OPTION 2:  LV, NO, AT, SE, DE - 5 votes
OPTION 2 to be realised in v1.1.0**

**Comment by peterlubrich** [comment]
when realizing OPTION 2: 
we need to adjust the Controlled Vocabulary ["Conditions for access and usage"](https://w3id.org/mobilitydcat-ap/conditions-for-access-and-usage).
I will open a corresponding issue [#22](https://github.com/mobilityDCAT-AP/controlled-vocabularies/issues/22) at the Controlled Vocab repository.

**Comment by peterlubrich** [comment]
OPTION 2 realized in v1.1.0: Respec updated
