### ISSUE TITLE
Check examples referenced by the specification

### ISSUE THREAD

**Issue by marioscrock** [mobilityDCAT-AP/mobilityDCAT-AP#29]
This sentence is added to the spec at the beginning of Section 4. These examples should be updated or removed. Moreover, paths should be relative and not absolute.

`Examples on the use of these properties, encoded in [[Turtle](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#bib-turtle)], are included in the relevant sections. The examples are also available in [[Turtle](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#bib-turtle)], RDF/XML [[RDF-SYNTAX-GRAMMAR](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#bib-rdf-syntax-grammar)], and JSON-LD [[JSON-LD11](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#bib-json-ld11)] from a [separate folder](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/examples/).`

**Comment by lcomet** [comment]
Closed with #24
