### ISSUE TITLE
SHACL shapes and controlled vocabularies

### ISSUE THREAD

**Issue by marioscrock** [mobilityDCAT-AP/mobilityDCAT-AP#30]
The mobilityDCAT-AP SHACL shape seems to contain a reference to not existing controlled vocabularies 

https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/c7249d844ac711b5d9ff0294ca1f50f27fa3d1cf/drafts/1.0.1-draft-0.1/mobilitydcatap_shacl_shapes_v1.0.0.ttl#L607

like https://w3id.org/mobilitydcat-ap/data-content-category and https://w3id.org/mobilitydcat-ap/service-category. 

I think this is an oversight due to the previous naming of the vocabularies. It does not seem to me that these vocabularies are referenced in the ReSpec page. The updated list of vocabularies is documented [here](https://github.com/mobilityDCAT-AP/controlled-vocabularies/blob/main/README.md).

**Comment by lcomet** [comment]
I updated the references to the controlled vocabularies with those specified [here](https://github.com/mobilityDCAT-AP/controlled-vocabularies/blob/main/README.md). This update applies to the latest draft version and the release version.
