### ISSUE TITLE
SHACL shapes how-to

### ISSUE THREAD

**Issue by marioscrock** [mobilityDCAT-AP/mobilityDCAT-AP#31]
Early adopters would like to have a dedicated paragraph in the Wiki explaining how to validate mobilityDCAT-AP metadata against the SHACL Shapes. @lcomet maybe you can suggest/explain the tool you used for the examples?

**Comment by lcomet** [comment]
I explained in the Wiki by adding question 13 https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/wiki/Chapter-2:-Recommendations-for-the-deployment-of-mobilityDCAT%E2%80%90AP#13-how-can-i-validate-my-data-against-the-mobilitydcat-ap-shacl-shape-file and also updating the answer for question 12.
