### ISSUE TITLE
Images not showing in HTML documentation

### ISSUE THREAD

**Issue by arthurKNTM** [mobilityDCAT-AP/mobilityDCAT-AP#32]
When I open the documentation (index.html), the images do not load correctly.

The images are located in a subfolder (mobilityDCAT-AP/releases/figures) while the index.html is contained in a folder above (mobilityDCAT-AP/releases/1.0.X)

To solve the issue, the figures folder could be copied into the folder of the different releases, or the reference in the release could be made to ../figures/[imagelocation].

**Comment by lcomet** [comment]
Thank you for reporting this issue. It is now solved.
