### ISSUE TITLE
Property Legal Framework does not exist GitHub

### ISSUE THREAD

**Issue by EdNDW** [mobilityDCAT-AP/mobilityDCAT-AP#33]
The property Legal Framework does not exist in the repository

**Comment by peterlubrich** [comment]
Hello Ed, @EdNDW 
I see this property is noted as "Applicable Legislation" in our v.1.0.1. spec.
See: https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#dataset-applicable-legislation

Peter

**Comment by peterlubrich** [comment]
Closed on meeting 24.06.24
