### ISSUE TITLE
Optional property for distribution: cnt:characterEncoding  wrong range 

### ISSUE THREAD

**Issue by JBeernaerts** [mobilityDCAT-AP/mobilityDCAT-AP#34]
The controlled vocab is not defined yet. 
If it is defined, the range should be changed to "skos:Concept(optional)"

**Comment by JBeernaerts** [comment]
+ the controlled vocabulary is missing.

**Comment by peterlubrich** [comment]
Good observation.
Our property "cnt:characterEncoding" is copied from the [same property in geoDCAT-AP v2](https://semiceu.github.io/GeoDCAT-AP/releases/#distribution-character-encoding):

In geoDCAT-AP v3, this property has the following usage note:

> It SHOULD be expressed using a character set name defined in the IANA register [IANA-CHARSETS](https://www.iana.org/assignments/character-sets).

This way, this is not really a Controlled Vocabulary, but a link to the IANA website.

Proposal:
1. Change the current usage note for our property "cnt:characterEncoding" from...

> A controlled vocabulary [§ 5.2 Controlled vocabularies to be used](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#controlled-vocabularies-to-be-used) is provided.

...to the exact formulation used in geoDCAT-AP above.

2. Correct in current version of  mobilityDCAT-AP as immediate troubleshooting

**Comment by peterlubrich** [comment]
Status 15.08.24:
I executed the proposal above. Usage notes is corrected. Issue to be closed.
