### ISSUE TITLE
Confusing triangular arrows in UML figures (resemble inheritance)

### ISSUE THREAD

**Issue by vlcinsky** [mobilityDCAT-AP/mobilityDCAT-AP#37]
Figure 1 Excerpt of mobilityDCAT-AP UML Class Diagram with focus on central classes

![](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/figures/mobilityDCAT-AP_uml-diagramm_230928_centralClasses.png)

is using arrows with triangular points. In UML this is used to point to the class being a parent of the child on the other side of the arrow.

But this is not the case (as there is cardinality mentioned) and it can confuse readers.

Consider rendering the diagram with proper symbols on ends of associations. Here I would guess a composition or aggregation, e.g:

- dcat:Catalog being a composition of (full ownership) dcat:CatalogRecord instances
- dcat:CatalogRecord embedding (composition of one) dca:tDataset
- dcat:Dataset being a composition of 1..n dcatDistribution instances.

The same (confusing triangular arrows) to all remaining figures showing UML class diagram.

**Comment by peterlubrich** [comment]
Thanks, Petr, I have corrected all UML figures with the proper symbols

**Comment by vlcinsky** [comment]
Hi @peterlubrich. Jan (vlcinsky) here. 
Thanks for the modification.

Now it is not confusing readers.

Anyway, if we want to use power of UML diagrams, we can denote, that something is owned by something else (in this case it is a composition - meaning full ownership - meaning that if an instance of owning class is deleted, it would take with it all owned items on the right side. In database terms it would be "cascade delete").

The composition is denoted by a filled diamond on the owner side.

![mobilityDCAT-AP-class-model drawio](https://github.com/user-attachments/assets/94f925f2-6998-459b-91b0-9a2755c4eca2)
