### ISSUE TITLE
Example files cannot be retrieved on ReSpec page

### ISSUE THREAD

**Issue by peterlubrich** [mobilityDCAT-AP/mobilityDCAT-AP#39]
If I click on any of the links in the [example section](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#examples), e.g. …
https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/examples/SE%20NAP_dataset_original%20in%20proprietary%20DCAT-AP_240205.xml
 
…I am receiving this error:
_404
File not found
The site configured at this address does not contain the requested file._
 
Please repair
Thanks!
Peter

**Comment by peterlubrich** [comment]
@Daham already analysed this issue. Response be email on June 20th:

_Hello Peter,
Regarding the issue with the links on the GitHub Pages for the mobilityDCAT-AP project, I've performed the following steps to investigate:
Cloned the project to my machine.
Project Structure:
C:\Users\mustafa\Desktop\mobilityDCAT-AP\mobilityDCAT-AP\releases\1.0.1
|-- examples\
|   |-- SE NAP_dataset_original in proprietary DCAT-AP_240205.xml
|   |-- SE NAP_dataset_expressed in mobilityDCAT-AP_original population_240205.xml
|   |-- SE NAP_dataset_expressed in mobilityDCAT-AP_original population_240205.ttl
|   |-- SE NAP_dataset_expressed in mobilityDCAT-AP_minimum population_240205.xml
|   |-- SE NAP_dataset_expressed in mobilityDCAT-AP_minimum population_240205.ttl
|-- index.html
|-- mobilitydcat-ap.jsonld
|-- mobilitydcat-ap.rdf
|-- mobilitydcat-ap.ttl
|-- mobilitydcat-ap_shacl_shapes.ttl

Steps Taken:

I navigated to the directory containing index.html.
I opened a terminal and ran a local HTTP server using the command: python -m http.server
I accessed the local server at http://localhost:8000/ in my web browser.
I confirmed that I could successfully navigate to index.html and that the links to the examples (SE NAP_dataset...) are functioning correctly.
Based on this local test, it appears that the project structure and the links within index.html are set up correctly. The issue might lie in the deployment or configuration of the GitHub Pages itself.
Could you please verify the following on the GitHub repository:
Ensure that the gh-pages branch is correctly configured with the examples directory and index.html.
Check that the relative paths in index.html accurately reference the files in the examples directory.
If there are any specific details or aspects you'd like me to further investigate, please let me know. I'm here to assist in resolving this issue promptly.
Daham_

**Comment by marioscrock** [comment]
@peterlubrich The `examples` folder was not copied into the `release` folder, so the relative paths were not working. It should be fixed now!
