### ISSUE TITLE
Suggested changes technical specification

### ISSUE THREAD

**Issue by JGBeernaerts** [mobilityDCAT-AP/mobilityDCAT-AP#4]
1. Line 45: replace 'Haarmonised' with 'harmonised'
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/fe40993843e51dbacf0d50591702a0382196812a/drafts/latest/index.html#L45

2. Line 88: replace 'Haarmonised' with 'harmonised'
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/fe40993843e51dbacf0d50591702a0382196812a/drafts/latest/index.html#L88

3. Line 101: correct 'wass' to 'was'
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/fe40993843e51dbacf0d50591702a0382196812a/drafts/latest/index.html#L101

4. Line 143: correct 'refereneced' to 'referenced'
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/fe40993843e51dbacf0d50591702a0382196812a/drafts/latest/index.html#L101

5. Line 160: remove duplicate sentence: 'In the context of mobility, this might be, e.g., a data collection about static parking information for truck drivers'
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/fe40993843e51dbacf0d50591702a0382196812a/drafts/latest/index.html#L160

6. Line 167: remove duplicate words in bold: 'A Metadata registry **is a A Metadata registry**'
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/fe40993843e51dbacf0d50591702a0382196812a/drafts/latest/index.html#L167

7. Line 167 (and following): Fix inconsistency in wording: 'data set' but before the term 'dataset' is used. Fix this inconsistency throughout the document (e.g. next occurence on Line 169). Suggestion to use wording 'dataset'.
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/fe40993843e51dbacf0d50591702a0382196812a/drafts/latest/index.html#L167

8. Line 184: delete comma in 'data portals, e.g., allowing' 
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/fe40993843e51dbacf0d50591702a0382196812a/drafts/latest/index.html#L184

9. Line 283: review if naming is correct: 'External assesment' mentioned here while later on only 'Assesment'.
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/fe40993843e51dbacf0d50591702a0382196812a/drafts/latest/index.html#L283

10. Line19 (Class assesment): Change & add text in bold 'to set up procedures to assess the compliance **of** the Delegated Regulations' with 'compliance **with** the **applicable** Delegated Regulations'
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/750e089f5297d6ce0b1c746917973a05b1344bd1/drafts/latest/tables/class-assessment.html#L19

**@peterlubrich: new as of 25/07/2023 below:**

11.  Line 52 (Class assesment): suggestion to remove 'draft' from the Optional property 'assesment result'
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/3a9b30deb9fc5563e609d2d97b8f007feb44a2e0/drafts/latest/tables/optional-properties-for-assessment.html#L52

12.  Line 70 (Class assesment): suggestion to remove 'draft' from the Optional property 'assesment report'
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/3a9b30deb9fc5563e609d2d97b8f007feb44a2e0/drafts/latest/tables/optional-properties-for-assessment.html#L70

13.  Line 70 (Class assesment): suggestion to remove 'external' from the Optional property 'assesment report' in order to generalise this property (e.g. use by data portals that are not NAPs or for NAPs that publish the report of the NB on the same hostname (website) as the NAP itself.)
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/3a9b30deb9fc5563e609d2d97b8f007feb44a2e0/drafts/latest/tables/optional-properties-for-assessment.html#L70

14. Line 54 (Class catalogue - mandatory properties): suggestion to change 'should' by 'could be generated by the system', I do not think this would give good results on a platform with multiple languages (such as BE NAP) where metadata could be entered in a language different from the language of the GUI (e.g. as many users are multilingual and might provide metadata in EN while viewing the webpage in one of their native languages NL, FR or DE)
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/9a7be840833700b66b0dc5e56783d0a9732ab9c6/drafts/latest/tables/mandatory-properties-for-catalogue-record.html#L54

15. Line 36: (Optional properties for dataset - Assesment result): suggestion to rephrase 'he property SHOULD point to the recent assessment procedure' to 'he property SHOULD point to the **most** recent assessment procedure' (addition in bold)
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/3fd5bb78fa24570caeb992847be41657de8add96/drafts/latest/tables/optional-properties-for-dataset.html#L36

16. Line 141: (Optional properties for dataset - identifier): Suggestion to change to mandatory (conform the conceptual model). A unique identifier for the dataset is essential for harvesting purposes. Please review why this was changed to an optional property.
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/3fd5bb78fa24570caeb992847be41657de8add96/drafts/latest/tables/optional-properties-for-dataset.html#L141

17. Line 38: Mandatory properties for Distribution: accessURL: review cardinality '1..n' not conform with conceptual model: only one accessURL for a distribution (if not it should be a seperate distribution for the dataset). Suggestion to change to '1..1'
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/3fd5bb78fa24570caeb992847be41657de8add96/drafts/latest/tables/mandatory-properties-for-distribution.html#L38

18. Line73: Mandatory properties for Distribution: format: spelling mistake in sentence 'There reason is the use'. Please correct 'There'.
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/3fd5bb78fa24570caeb992847be41657de8add96/drafts/latest/tables/mandatory-properties-for-distribution.html#L73

19. Line 73: Recommended properties for Distribution: The example shown 'e.g., DATEX II v3.2.' does not specify whether the full format (which would be mandatory property dct:format for the Distribution) plus the version number should be mentioned (in the example: DATEX II v3.2), or only the version number (in the example: (v)3.2). Please clarify this
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/3fd5bb78fa24570caeb992847be41657de8add96/drafts/latest/tables/recommended-properties-for-distribution.html#L73

20. Line 137 (and below): Optional properties for distribution: data format notes: missing range definition. Suggestion to add 'rdfs:Literal'. 
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/3fd5bb78fa24570caeb992847be41657de8add96/drafts/latest/tables/optional-properties-for-distribution.html#L137

21. Line 186: Optional properties for distribution: DowloadURL cardinality '0..n' not conform conceptual model '0..1'. Please review/change.
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/3fd5bb78fa24570caeb992847be41657de8add96/drafts/latest/tables/optional-properties-for-distribution.html#L186

**Comment by peterlubrich** [comment]
Dear Jasper,
Thank you very much for your review.
I addressed your comments as follows:

1-15. Wording corrected as suggested
16. Idea dismissed. We discussed that the main identificator of a dataset should be the URI used within the RDF statement (via rdf:about). The additional property "identifier" might be used for special identification purposes (maybe with a future EU-wide identificator concept developed by mobilityDCAT-AP). To make this clearer, the usage note for property "indentifier" has been concretised.
17. Cardinality changed to '1..1'
18. Wording corrected as suggested
19. Usage note for property "data model version" has been concretised.
20. rdfs:Literal has been added as Range
21. Cardinality changed to '0..1'

Best,
Peter
