### ISSUE TITLE
"Title" Syntax is missing in standard description V1.0.1

### ISSUE THREAD

**Issue by BWitsch** [mobilityDCAT-AP/mobilityDCAT-AP#46]
![grafik](https://github.com/user-attachments/assets/021d7b0f-58d3-4359-8c72-81fce8841ed1)

**Comment by peterlubrich** [comment]
@BWitsch: I dont understand the problem. 
Do you want to change the title of this property "dct:format"?
Please note that we copied this property from DCAT-AP v2.0.1. We only expanded the usage note (the right column in the screenshot) to clarify what it technically means.
