### ISSUE TITLE
Example File Review for SHACL Shape Validation

### ISSUE THREAD

**Issue by Daham-Mustaf** [mobilityDCAT-AP/mobilityDCAT-AP#50]
# Create Example File for SHACL Shape Validation

## Objective
Create an example file to validate each shape in our current SHACL shapes. This will help improve the implementation of our shapes without altering their intended meaning.

## Tasks
1. Develop example data for each SHACL shape
2. Validate the examples against corresponding shapes
3. Document the validation process and results

## Expected Outcome
- Improved SHACL shape implementations
- Comprehensive validation examples
- Clear documentation of the validation process

**Comment by peterlubrich** [comment]
Status 27.08.:

- Daham did testing with SHACL shapes
- bilateral call Daham with Peter on August 30 about test results
- later in 2024: online class to SWG 4.4 about SHACL validation

**Comment by peterlubrich** [comment]
Status 30.08.:
I see two current work items for Daham:
1. Production of test files for each class being validated (including a generic description about this test suite, and individual TTL files with correct&incorrect class instances, including explanations)
2. Review and update of the current mobilityDCAT-AP SHACL file (TTL). It seems that some ranges of some properties might be improved/replaced. Daham will analyse this and summarise update proposals.
 
The results from 1. and 2. will be provided later on the mobilityDCAT-AP repository, so deployers can reuse it.

**Comment by peterlubrich** [comment]
> 1. Production of test files for each class being validated (including a generic description about this test suite, and individual TTL files with correct&incorrect class instances, including explanations)
> 2. Review and update of the current mobilityDCAT-AP SHACL file (TTL). It seems that some ranges of some properties might be improved/replaced. Daham will analyse this and summarise update proposals.

These two work items have been realised via  the recent [pull request #60 ](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/pull/60), as well as [issue #54](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/54)

Means the updated SHACL file under mobilityDCAT-AP v1.1.0 will reflect these work items.
I am closing this issue.
