### ISSUE TITLE
GeoVocab.org (Reference for Linked Open Data for NUTS codes) is now longer available (=>now online gaming site)

### ISSUE THREAD

**Issue by PartTimeDataScientist** [mobilityDCAT-AP/mobilityDCAT-AP#53]
The [reference](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/23ab3a89277a8da3f27e96893fb0ff755b1537d9/releases/index.html#L838-L845) to the linked [NUTS-RDF project](http://nuts.geovocab.org/) is no longer available and the parent site hxxps://geovocab.org seems to be some kind of online gambling site now.

Could possibly replaced by the official [EU Dataset](https://data.europa.eu/data/datasets/estat-nuts-classification)

**Comment by marioscrock** [comment]
@PartTimeDataScientist thank you for raising this point! I close this issue and we can continue the discussion in #58
