### ISSUE TITLE
Update Property Ranges from owl:Thing to More Specific Datatypes

### ISSUE THREAD

**Issue by Daham-Mustaf** [mobilityDCAT-AP/mobilityDCAT-AP#54]
# Update Ontology Property Ranges for Improved Data Integrity

## Issue Description

Several properties in our ontology currently use `owl:Thing` as their range, which is overly generic and does not enforce the intended data types. This can lead to semantic ambiguities and reduced data integrity. To enhance clarity and ensure proper data validation, it's recommended to specify more precise ranges for these properties.

## Affected Properties and Proposed Alternatives

1. `vcard:hasEmail` (+email)
   * **Current Range:** `owl:Thing`
   * **Proposed Range:** `xsd:anyURI`
   * **Reason:** Ensures that the email address follows the `mailto:` URI scheme as per RFC6068.

2. `vcard:hasURL` (+URL)
   * **Current Range:** `owl:Thing`
   * **Proposed Range:** `xsd:anyURI`
   * **Reason:** Validates that the property points to a well-formed web URL.

3. `vcard:hasTelephone` (+phone)
   * **Current Range:** `owl:Thing`
   * **Proposed Range:** `xsd:anyURI`
   * **Reason:** Ensures the phone number follows the `tel:` URI scheme as specified by RFC3966.

4. `foaf:mbox` (email)
   * **Current Range:** `owl:Thing`
   * **Proposed Range:** `xsd:anyURI`
   * **Reason:** Aligns with using `mailto:` URIs for email addresses, enhancing semantic precision.

5. `foaf:phone` (+phone)
   * **Current Range:** `owl:Thing`
   * **Proposed Range:** `xsd:anyURI`
   * **Reason:** Ensures the phone number is specified using the `tel:` URI scheme, maintaining consistency with related properties.

## References

* [RFC6068 - The `mailto` URI Scheme](https://tools.ietf.org/html/rfc6068)
* [RFC3966 - The `tel` URI Scheme](https://tools.ietf.org/html/rfc3966)
* [XML Schema Datatypes (`xsd:anyURI`)](https://www.w3.org/TR/xmlschema-2/#anyURI)

**Comment by marioscrock** [comment]
@Daham-Mustaf I agree with the overall idea, but it is usually bad practice to restrict ranges of properties from external ontologies (as in the cases proposed). We can add in our specification usage notes that specify the fact that the range should be compliant with the proposed ranges and then model SHACL shapes that raise warnings in case this is not respected. What do you think?

**Comment by Daham-Mustaf** [comment]
@marioscrock  I agree that we should keep the ontology as is, with `owl:Thing` as the range. `owl:Thing` being the root class provides flexibility in the ontology. Instead of modifying the ontology, we'll use SHACL shapes to enforce the proposed data types for these properties.

For example, for `foaf:phone`, we'll implement a SHACL shape like this:

```turtle
ex:FoafPhoneShape a sh:NodeShape ;
  sh:targetClass foaf:Agent ;
  sh:property [
    sh:path foaf:phone ;
    sh:nodeKind sh:IRI ;
    sh:pattern "^tel:.+" ;
  ] .
```

This enforces the `tel:` URI scheme without altering the original ontology. We'll apply similar SHACL shapes for other properties as needed. Does this make sense to you?

**Comment by marioscrock** [comment]
Yes, exactly! Maybe you can check if there are already similar shapes defined for DCAT-AP 👍 https://semiceu.github.io/DCAT-AP/releases/3.0.0/#validation-of-dcat-ap

**Comment by peterlubrich** [comment]
I see the above proposal (changing the SHACL values from "owl:Thing" to "sh:IRI") has been realised in the recent [pull request #60 ](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/pull/60). 

Means:

- We have an updated "mobilitydcat-ap_shacl_shapes.ttl"
- We will publish this update together with upcoming mobilityDCAT-AP v1.1.0
- We close this issue
