### ISSUE TITLE
class MobilityDataStandard: property "scheme"

### ISSUE THREAD

**Issue by peterlubrich** [mobilityDCAT-AP/mobilityDCAT-AP#56]
The [property "mobilitydcatap:scheme](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#mobility-data-standard-schema) has a cardinality : 0..1
Because in some cases, multiple schemes can be provided per data set, especially in DATEX II v3:
I propose to change the cardinality to 0..n

**Comment by marioscrock** [comment]
I agree! Not sure if, in this case, we have to specify somehow better the semantics of the property when more than one schema is provided, e.g., "the data are compliant with at least/all/? the schemes provided"

**Comment by peterlubrich** [comment]
Proposal for v1.1.0:

- Change cardinality at [mobilitydcatap:schema](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/index.html#mobility-data-standard-schema).
- At the same time, add to Usage Note that this property is a sub-property of [dct property "conformsTo"](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#conformsTo)

**Comment by peterlubrich** [comment]
Meeting 05.12.2024:
Decision procedure for the proposed change:

_Cardinality of property ["schema"](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#mobility-data-standard-schema) changed from from 0..1 to 0..n. Reason: allow for naming multiple schemas.  DECISION POINT: YES / NO_

**Decision result: no opposition, change to be realised in v1.1.0**

**Comment by peterlubrich** [comment]
Realised in v1.1.0: Updated Respec,  SHACL file
