### ISSUE TITLE
Wrong reference to NUTS vocabulary

### ISSUE THREAD

**Issue by peterlubrich** [mobilityDCAT-AP/mobilityDCAT-AP#58]
Under [chapter 5.2](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#controlled-vocabularies-to-be-used), we reference to a defunctional NUTS RDF vocabulary:
http://nuts.geovocab.org/

This has to be replaced by this EU NUTS vocabulary:
https://op.europa.eu/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/nuts

**Comment by marioscrock** [comment]
I moved here since it does not refer to vocabularies in the controlled-vocabularies folder but to an external vocabulary mentioned by the spec. Agree with the replacement 👍

**Comment by marioscrock** [comment]
Related to #53 

> The [reference](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/23ab3a89277a8da3f27e96893fb0ff755b1537d9/releases/index.html#L838-L845) to the linked [NUTS-RDF project](http://nuts.geovocab.org/) is no longer available and the parent site hxxps://geovocab.org seems to be some kind of online gambling site now.
> 
> Could possibly replaced by the official [EU Dataset](https://data.europa.eu/data/datasets/estat-nuts-classification)

**Comment by peterlubrich** [comment]
Repaired under draft for [v1.0.1](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/index.html#changes-since-20240424), issue to be closed
