### ISSUE TITLE
Reorganize and fix URLs to resolve content

### ISSUE THREAD

**Issue by lcomet** [mobilityDCAT-AP/mobilityDCAT-AP#6]
Consider the draft and published versions only. 
https://w3id.org/mobilitydcat-ap/releases/ and https://w3id.org/mobilitydcat-ap/releases/1.0/ should be resolved accordingly.
Once the identifier "mobilitydcat-ap" under w3id is available: 

1. Fix the URL from https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/ to https://w3id.org/mobilitydcat-ap/drafts/latest/ in the Readme file. 
2. Check the redirecting of the URLs

**Comment by marioscrock** [comment]
Fix links in https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/gh-pages/drafts/README.md

**Comment by lcomet** [comment]
Links are fixed, and the redirections work.
