### ISSUE TITLE
Class MobilityDataStandard: expected usage and new property  `conformsTo`

### ISSUE THREAD

**Issue by marioscrock** [mobilityDCAT-AP/mobilityDCAT-AP#65]
The expected usage of the property `mobilitydcatap:mobilityDataStandard` should be clarified in the spec as discussed in #35 and #36. In the example provided within the spec, we have

```turtle
<https://www.trafficdata.se/dataset/ec459578-a11f-4728-acaa-16b08ae45cfa/resource/4d2cccaf-219f-4fe6-a22c-d695ce86699d>
  a dcat:Distribution ;
  [...]
  mobilitydcatap:mobilityDataStandard <https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II> ;
```
This is correct, and I would vote to keep this alternative (first approach) valid. However, in some cases the user may want to specify further the data standard of the distribution by instantiating an individual of class MobilityDataStandard (second approach).

In the RDF serialisation of the spec, we have `dcam:rangeIncludes` and not `rdfs:range` spec for the `mobilityDataStandard` property to enable both the adoption of a simple value from the `mobility-data-standard ` controlled vocabulary or the creation of a "custom value" as an instance of the class `MobilityDataStandard`. Regarding the first approach (in the example above) we should:

- [ ] add `dcam:rangeIncludes skos:Concept` for the `mobilityDataStandard` property, as done for other properties referencing a controlled vocabulary. 
- [ ] change the SHACL shapes to accept this behaviour (currently an individual of class MobilityDataStandard is expected in any case)

Regarding the second approach an example is:

```turtle
<https://www.trafficdata.se/dataset/ec459578-a11f-4728-acaa-16b08ae45cfa/resource/4d2cccaf-219f-4fe6-a22c-d695ce86699d>
  a dcat:Distribution ;
  [...]
  mobilitydcatap:mobilityDataStandard <https://www.trafficdata.se/standard/datex-ii-se-profile-v3.2> .

<https://www.trafficdata.se/standard/datex-ii-se-profile-v3.2> a mobilitydcatap:MobilityDataStandard ;
  owl:versionInfo "3.2" ;
  dct:conformsTo <https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II>;
  mobilitydcatap:schema "...URL leading to schema file(s)..." .
```
A custom instance of class `mobilitydcatap:MobilityDataStandard` is defined (as shown above for `<https://www.trafficdata.se/standard/datex-ii-se-profile-v3.2>`). For this approach we should:

- [ ] include dct:conformsTo as property for class `MobilityDataStandard` to reference the appropriate value from the  `mobility-data-standard ` controlled vocabulary  (in the example `https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II`)
- [ ] adapt the RDF serialization and the SHACL shapes accordingly

**Comment by peterlubrich** [comment]
I have realized an [additional property "dct:conformsTo" in the current draft of v1.1.0](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#mobility-data-standard-standard-name)

**Comment by Daham-Mustaf** [comment]
@marioscrock Thank you for raising this issue regarding the `mobilityDataStandard` property usage. I agree with your analysis and proposal to support both approaches. I've prepared a SHACL shape update that implements these requirements:

### Proposed Solution

The updated SHACL shapes support both approaches:

1. **Direct reference to controlled vocabulary** (first approach):
```turtle
<https://www.trafficdata.se/dataset/ec459578-a11f-4728-acaa-16b08ae45cfa/resource/4d2cccaf-219f-4fe6-a22c-d695ce86699d>
  a dcat:Distribution ;
  mobilitydcatap:mobilityDataStandard <https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II> ;
```

2. **Custom MobilityDataStandard instance** (second approach):
```turtle
<https://www.trafficdata.se/dataset/ec459578-a11f-4728-acaa-16b08ae45cfa/resource/4d2cccaf-219f-4fe6-a22c-d695ce86699d>
  a dcat:Distribution ;
  mobilitydcatap:mobilityDataStandard <https://www.trafficdata.se/standard/datex-ii-se-profile-v3.2> .

<https://www.trafficdata.se/standard/datex-ii-se-profile-v3.2> 
  a mobilitydcatap:MobilityDataStandard ;
  owl:versionInfo "3.2" ;
  dct:conformsTo <https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II> ;
  mobilitydcatap:schema "...URL leading to schema file(s)..." .
```

Here's the updated SHACL shape that validates both patterns:

```turtle
:Distribution_Shape
  a sh:NodeShape ;
  sh:property [
    sh:minCount 1 ;
    sh:maxCount 1 ;
    sh:path mobilitydcatap:mobilityDataStandard ;
    sh:or (
      # First approach: Direct reference to controlled vocabulary
      [
        sh:nodeKind sh:IRI ;
        sh:pattern "^https://w3id.org/mobilitydcat-ap/mobility-data-standard/"
      ]
      # Second approach: Reference to MobilityDataStandard instance
      [
        sh:class mobilitydcatap:MobilityDataStandard
      ]
    ) ;
    sh:severity sh:Violation
  ] .

# Updated MobilityDataStandard shape
:MobilityDataStandard_Shape
  a sh:NodeShape ;
  sh:property [
    sh:nodeKind sh:IRI ;
    sh:pattern "^https://w3id.org/mobilitydcat-ap/mobility-data-standard/" ;
    sh:path dct:conformsTo ;
    sh:maxCount 1 ;
    sh:severity sh:Violation
  ] .
```


1. Updated the Distribution shape to support both patterns using `sh:or`
2. Added `dct:conformsTo` to the MobilityDataStandard shape to reference the controlled vocabulary

**Comment by peterlubrich** [comment]
@Daham-Mustaf : thank you for the SHACL updates. I have inserted these updates into the [latest draft version of the SHACL file](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/gh-pages/drafts/latest/validationFiles/mobilitydcat-ap_shacl_shapes.ttl) .

**Comment by peterlubrich** [comment]
Meeting 05.12.2024:
Decision procedure for the proposed change:

_Property [dct:conformsTo](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#mobility-data-standard-standard-name) added under [optional properties for Class Mobility Data Standard](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#optional-properties-for-mobility-data-standard). This property describes the name of the mobility data standard. This property is used when a custom instance of class mobilitydcatap:MobilityDataStandard is defined, see the usage note for this property.  DECISION POINT: YES / NO_

**Decision result: no opposition, change to be realised in v1.1.0**

**Comment by peterlubrich** [comment]
Realised in v1.1.0: Updated Respec, serialisation files, SHACL file
