### ISSUE TITLE
Remove unused files from GeoDCAT-AP

### ISSUE THREAD

**Issue by marioscrock** [mobilityDCAT-AP/mobilityDCAT-AP#8]
Remove unused files from GeoDCAT-AP, e.g., https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/gh-pages/drafts/latest/appendices/inspire-and-iso-19115-mappings.html

**Comment by peterlubrich** [comment]
Good point, Mario,
in the Code section of our repository, you will find many html files that are originally from the geoDCAT-AP specification, but not used in the current mobilityDCAT-AP spec.

In the "appendices" folder: 
inspire-and-iso-19115-mappings.html -> can be deleted

In the "examples" folder:
None of the files is used. However, we need to elaborate our own examples in the future. -> Keep this folder as a template.

In the "tables" folder:
change-log.htm -> please keep as a template for a future change log of mobilityDCAT-AP 
change-log.html.dcat-ap -> can be deleted
class-activity.html  -> can be deleted
class-address-kind.html -> can be deleted
class-attribution.html  -> can be deleted
class-metric.html -> can be deleted
class-quality-measurement.html -> can be deleted
dcat-ap-wg-members.html  -> can be deleted
deprecated-....html (8 files)  -> can be deleted
instances-of-metric.html  -> can be deleted
optional-properties-for-kind.html  -> can be deleted
optional-properties-for-period-of-time.html -> can be deleted
optional-properties-for-standard.html -> can be deleted
quick-reference-of-classes-and-properties.html.dcat-ap -> can be deleted
recommended-properties-for-address-kind.html -> can be deleted
recommended-properties-for-document.html -> can be deleted
recommended-properties-for-kind.html -> can be deleted
recommended-properties-for-media-type.html -> can be deleted
recommended-properties-for-metric.html -> can be deleted
recommended-properties-for-provenance-statement.html -> can be deleted
recommended-properties-for-quality-measurement.html  -> can be deleted
recommended-properties-for-standard.html -> can be deleted

**Comment by peterlubrich** [comment]
Mario,
please have a look at my analysis of the "unused html files" above, and feel free to delete the files that I noted with "can be deleted".
Thanks!

**Comment by marioscrock** [comment]
> Mario, please have a look at my analysis of the "unused html files" above, and feel free to delete the files that I noted with "can be deleted". Thanks!

Thank you Peter, done! Now the `appendices` folder is empty (should we move CMC-mappings there?). I didn't change the files in the `examples` folder. I kept the changelog as a template in the file `change-log.html.geodcat-ap`.
