### ISSUE TITLE
Define folder structure for versioned drafts/releases

### ISSUE THREAD

**Issue by marioscrock** [mobilityDCAT-AP/mobilityDCAT-AP#9]
The current .htaccess defined for w3id takes into account the structure of versioned drafts/releases of GeoDCAT-AP. To be discussed if something should be changed.

For example versioned drafts are saved as drafts/1.1-draft-0.1, i.e., drafts/_version_-draft-0.1

**Comment by peterlubrich** [comment]
In my opinion, we should follow the geoDCAT-AP approach for the structuring of drafts/releases.

For now, we have ONE draft of mobilityDCAT-AP, which is currently being updated based on the incoming reviews.
This draft should be closed and converted into a release v1.0 in october 2023.

* do we have a version number for this draft?

**Comment by marioscrock** [comment]
@lcomet @peterlubrich I noticed that you're referring to the next release as 1.0. Currently, the redirect rules that I defined for w3id match a `major.minor.patch` format for releases such as 1.0.0 (as for DCAT-AP). 

https://w3id.org/mobilitydcat-ap/releases/1.0/ -> redirects to the wrong URL
https://w3id.org/mobilitydcat-ap/releases/1.0.0 -> redirects to the right URL (currently not working but only because the file doesn't exist)

Let me know if it is ok to use 1.0.0

**Comment by lcomet** [comment]
I will update the files with version 1.0.0.

**Comment by marioscrock** [comment]
To be checked for releases after v1.0.0 publication

**Comment by marioscrock** [comment]
@lcomet The link https://w3id.org/mobilitydcat-ap/drafts/1.0.0 redirects to https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/1.0.0-draft-0.1/index.html (it takes the version x.y.z after drafts/ in the first URL and composes the second URL). Currently, it does not work because there is no index.html file in the directory.
However, I will add a rule to handle also the https://w3id.org/mobilitydcat-ap/drafts/1.0.0-draft-0.1/. I think it makes sense because currently there is no way to access a hypothetical version 1.0.0-draft-0.2.

**Comment by marioscrock** [comment]
Done in https://github.com/perma-id/w3id.org/pull/3641
